<?php 
	include "_config.php";
	

	$controle = getGET('controle');
	$acao = getGET('acao');
	if( $controle == "busca")
 	{
 		if( $acao == "timeline")
 		{
 				echo json_encode( array( array("id"=> 0,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 1,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 2,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 3,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 4,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 5,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 6,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 7,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 8,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 9,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 10,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 11,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 12,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 13,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 14,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 15,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 16,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ),
	array("id"=> 17,  "titulo"=> "asdadasd", "data"=> array( '10-01-2016', '09-09-2015' ), "icone"=> "https://codyhouse.co/demo/vertical-timeline/img/cd-icon-picture.svg", "conteudo"=>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut." ) ) );
	
 		}

 	}